// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Les migrations (`prisma migrate deploy`) utilisent DIRECT_URL si
    // défini, sinon DATABASE_URL. Sur Neon, DATABASE_URL pointe vers
    // l'endpoint *poolé* (-pooler, pour le runtime serverless) qui ne
    // supporte pas les opérations DDL longues ; DIRECT_URL pointe vers
    // l'endpoint direct, requis pour les migrations. En local (Postgres
    // simple), laisser DIRECT_URL vide → fallback DATABASE_URL.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
